[#13] 관리자는 영화관을 추가할 수 있다
prgrms-be-devcourse/BE-02-MarBox pull request #28
Opened 2022-06-21 14:24 UTC by wisehero

## 개요
관리자 영화관 추가 

## 추가기능
createTheater() 메서드로 영화관 추가

## 기타
이렇게 보내는게 맞나 싶네요...

2022-06-22 05:41 UTC, Pawer0223 reviewed
고생하셨습니다 !

2022-06-22 05:41 UTC, Pawer0223 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +	public Theater() {
default 생성자가 public으로 두신 이유가 있을까요 ?!

2022-06-22 05:41 UTC, Pawer0223 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +	public Theater(String region, String name) {
Theater는 Region정보가 필수라는 도메인규칙을 enum 타입 생성자를 통해 강제하는것도 괜찮을것 같다는 의견입니다.

2022-06-22 05:41 UTC, Pawer0223 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +		return new EqualsBuilder().append(getId(), theater.getId())
저는 Entity가 식별자를 통해 구별할 수 있는 객체로 이해하고 있습니다. 따라서 id로만 equals, hashCode를 구현해야 올바른 식별이 가능하다는 의견입니다. 
현재 구조에서는 발생할 수 있는 Region, Name의 중복을 equals가 아닌 테이블 제약조건이라던지..? 다른 방안으로 해결하는게 적절하지 않을까라는 의견입니다.

2022-06-22 05:41 UTC, Pawer0223 commented on src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterServiceTest.java
> +			() -> assertThat(findTheater.getId()).isEqualTo(1L),
개인적으로 항상 생성 된 id가 1이라는것을 보장할 수 있는지 불안함이 존재하여, 테스트가 깨질 가능성이 있지 않을까라는 의견입니다.
1L보다는 savedTheaterId를 expect하는것이 안전할것 같다는 의견입니다.

2022-06-22 06:23 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +	public Theater() {
@Pawer0223 인텔리제이 단축키 사용 시 자동으로 public으로 해준 부분을 건드리지 않았습니다. 객체의 무분별한 생성을 방지하기 위해서 protected로 변경하는 게 낫겠네요!

2022-06-22 06:24 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +	public Theater(String region, String name) {
@Pawer0223 컨트롤러에서 RequestBody 애노테이션을 사용하지 않아 NPE가 뜨던 것을 해결하기 위해 이것저것 시도해보다가 원복하지 않은 내용이네요 감사합니다!

2022-06-22 06:28 UTC, Pawer0223 requested changes
@Transactional !

2022-06-22 06:28 UTC, Pawer0223 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
> +	public Long createTheater(RequestCreateTheater request) {
@Transactional이 추가되어야 할것 같습니다 !

2022-06-22 06:39 UTC, yanJuicy commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
> +public class RequestCreateTheater {
record로 바꾸시졍

2022-06-22 06:39 UTC, yanJuicy commented on src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
> +	public Long createTheater(RequestCreateTheater request) {
`@Transacational` 을 붙이시졍

2022-06-22 06:39 UTC, wisehero commented on src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterServiceTest.java
> +			() -> assertThat(findTheater.getId()).isEqualTo(1L),
@Pawer0223  저는 기대하는 값은 변수나 필드를 사용하지 않고 명시적으로 하는게 맞다고 생각합니다.

2022-06-22 06:39 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +		return new EqualsBuilder().append(getId(), theater.getId())
@Pawer0223 https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/EqualsBuilder.html 저는 공식문서를 참고했을 때 연관된 모든 필드가 equlas 계산에 들어가야 한다고 써져 있는 것을 참고했습니다.

2022-06-22 06:40 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
> +	public Long createTheater(RequestCreateTheater request) {
@Pawer0223 오우 빼먹었네요 감사합니다!

2022-06-22 06:57 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
> +public class RequestCreateTheater {
@yanJuicy 옙!

2022-06-22 12:52 UTC, Pawer0223 approved these changes
고생하셨습니다 !

2022-06-22 13:58 UTC, yanJuicy commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
> +	public RequestCreateTheater(String region, String name) {
레코드는 자동으로 생성자를 만들어주지 않나요?
https://velog.io/@gilchris/Java-Record

2022-06-22 13:58 UTC, yanJuicy commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
> +	public String region() {
getter 형태의 함수도 자동으로 만들어주는 걸로 알고 있습니다.
그대로 region과 name을 반환해주는것 같은데 override한 이유가 있으신가여??

2022-06-22 14:30 UTC, wisehero commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/RequestCreateTheater.java
> +	public RequestCreateTheater(String region, String name) {
@yanJuicy 자동 변환 후에도 남아있길래 문제가 생길까봐 남겨두었습니다!

2022-06-23 05:40 UTC, merged

2022-06-23 14:20 UTC, ksy90101 commented on build.gradle
> +}
new line은 관행적으로 작성해주시는게 좋아요~

2022-06-23 14:20 UTC, ksy90101 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/Theater.java
> +	@NotBlank
String이 아닌데 이 validate가 맞나요?

2022-06-23 17:20 UTC, wisehero commented on build.gradle
> +}
@ksy90101  checkStyle 빌드에러가 계속나서 어떻게 해줘야하는지 모르고 있었는데 IDE가 개행을 계속해서 없애도록 했더군요ㅠㅠ 설정 바꿔서 잘 작성되도록 했습니다!