[#14] 모든 상영관 정보를 조회할 수 있다.
prgrms-be-devcourse/BE-02-MarBox pull request #38
Opened 2022-06-23 12:52 UTC by Pawer0223

## 개요
- 모든 상영관 정보 조회

## 추가기능
- 모든 상영관 정보할 수 있다.

## 기타
- controller 미구현

2022-06-23 13:57 UTC, yanJuicy requested changes
저도 에러 메시지 문자열 상수로 빼야겠네용. approve 입니당

2022-06-23 13:58 UTC, yanJuicy approved these changes
approve

2022-06-23 14:42 UTC, wisehero approved these changes
approve

2022-06-24 00:25 UTC, hyuk0309 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/ResponseFindTheaterRoom.java
> +public record ResponseFindTheaterRoom(ResponseFindTheater responseFindTheater,
프론트 개발자 입장에서는 responseFindTheater 보다는 theater로 넘겨주는게 가독성이 좋지 않을까요? 🤔

2022-06-24 00:25 UTC, hyuk0309 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterRoomService.java
> +		return theaterRoomRepository.findAll().stream()
추후에 페이징 처리도 고려할 수 있을 것 같아요! 🙋‍♂️

2022-06-24 00:25 UTC, hyuk0309 commented on src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterRoomServiceTest.java
> +		log.info("result : {}", theaterRoomList);
개발할 때는 필요한 코드지만, 테스트 자동화에는 필요 없는 코드 아닐까요? 🤔

2022-06-24 00:25 UTC, hyuk0309 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/service/utils/TheaterRoomConverter.java
> +			theaterRoom.getTotalAmount()
👍

2022-06-24 06:53 UTC, Pawer0223 commented on src/main/java/prgrms/marco/be02marbox/domain/theater/dto/ResponseFindTheaterRoom.java
> +public record ResponseFindTheaterRoom(ResponseFindTheater responseFindTheater,
엇, 신경을 못썼네요 ! 감사합니다 !

2022-06-24 07:10 UTC, merged